"""Add published_at column to feature_files

Revision ID: 7cfd8a00bc35
Revises: 2991bee55e91
Create Date: 2025-11-27 21:29:06.820873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cfd8a00bc35'
down_revision: Union[str, None] = '2991bee55e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_files', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_files', 'published_at')
    # ### end Alembic commands ###
