"""Add approval fields to feature_files

Revision ID: f621b5e4e51f
Revises: 7cfd8a00bc35
Create Date: 2025-11-27 22:39:10.662171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f621b5e4e51f'
down_revision: Union[str, None] = '7cfd8a00bc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_files', sa.Column('submitted_for_approval_at', sa.DateTime(), nullable=True))
    op.add_column('feature_files', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('feature_files', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'feature_files', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feature_files', type_='foreignkey')
    op.drop_column('feature_files', 'approved_at')
    op.drop_column('feature_files', 'approved_by')
    op.drop_column('feature_files', 'submitted_for_approval_at')
    # ### end Alembic commands ###
